server:
  port: 80
#根据服务器实际路径进行更换，必须保留"/uploadFile/"
file-save-path: /Users/xiaohua/Desktop/Codes/cloud_image/uploadFile/
spring:
  thymeleaf:
    #去除thymeleaf的html严格校验
    mode: HTML
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/cloud_image?serverTimezone=UTC
      url: jdbc:mysql://172.21.21.101:30306/cloud_image?serverTimezone=UTC
      #      根据数据库实际账户和密码进行更换
      username: root
#      password: root
      password: 123456
  mail:
    host: smtp.qq.com
    username: 1805303088@qq.com
    password: sgqcdgpbfkmfcbhf
    default-encoding: utf-8
    protocol: smtp
    port: 465
    properties:
     mail:
      smtp:
        auth: true
        socketFactory.class: javax.net.ssl.SSLSocketFactory
  freemarker:
    template-loader-path: classpath:/templates
  #修改上传文件大小
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

mybatis-plus:
  configuration:
    #上线之后不能开，增大服务器压力
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #数据库id自增设置，MP有自己的id策略
      id-type: auto
